/*----------------------------------------------------------------------
 * This file is generated by mk_parser.py.
 *----------------------------------------------------------------------*/
#include <assert.h>
#include <stdint.h>
#include <stdio.h>
#include "cparser.h"
#include "cparser_priv.h"
#include "cparser_token.h"
#include "cparser_tree.h"

cparser_result_t
cparser_glue_add__s (cparser_t *parser)
{
    cparser_cmd_add__s(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_add__s__i_interval__f_filename (cparser_t *parser)
{
    int32_t interval_val;
    int32_t *interval_ptr = NULL;
    char *filename_val;
    char **filename_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_int(&parser->tokens[3], &interval_val);
    assert(CPARSER_OK == rc);
    interval_ptr = &interval_val;
    rc = cparser_get_string(&parser->tokens[5], &filename_val);
    if (CPARSER_OK == rc) {
        filename_ptr = &filename_val;
    } else {
        assert(6 > parser->token_tos);
    }
    cparser_cmd_add__s__i_interval__f_filename(&parser->context,
        interval_ptr,
        filename_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_add__s__f_filename__i_interval (cparser_t *parser)
{
    char *filename_val;
    char **filename_ptr = NULL;
    int32_t interval_val;
    int32_t *interval_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[3], &filename_val);
    assert(CPARSER_OK == rc);
    filename_ptr = &filename_val;
    rc = cparser_get_int(&parser->tokens[5], &interval_val);
    if (CPARSER_OK == rc) {
        interval_ptr = &interval_val;
    } else {
        assert(6 > parser->token_tos);
    }
    cparser_cmd_add__s__f_filename__i_interval(&parser->context,
        filename_ptr,
        interval_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_add__p_pid (cparser_t *parser)
{
    int32_t pid_val;
    int32_t *pid_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_int(&parser->tokens[2], &pid_val);
    assert(CPARSER_OK == rc);
    pid_ptr = &pid_val;
    cparser_cmd_add__p_pid(&parser->context,
        pid_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_add__p_pid__i_interval__f_filename (cparser_t *parser)
{
    int32_t pid_val;
    int32_t *pid_ptr = NULL;
    int32_t interval_val;
    int32_t *interval_ptr = NULL;
    char *filename_val;
    char **filename_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_int(&parser->tokens[2], &pid_val);
    assert(CPARSER_OK == rc);
    pid_ptr = &pid_val;
    rc = cparser_get_int(&parser->tokens[4], &interval_val);
    assert(CPARSER_OK == rc);
    interval_ptr = &interval_val;
    rc = cparser_get_string(&parser->tokens[6], &filename_val);
    if (CPARSER_OK == rc) {
        filename_ptr = &filename_val;
    } else {
        assert(7 > parser->token_tos);
    }
    cparser_cmd_add__p_pid__i_interval__f_filename(&parser->context,
        pid_ptr,
        interval_ptr,
        filename_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_add__p_pid__f_filename__i_interval (cparser_t *parser)
{
    int32_t pid_val;
    int32_t *pid_ptr = NULL;
    char *filename_val;
    char **filename_ptr = NULL;
    int32_t interval_val;
    int32_t *interval_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_int(&parser->tokens[2], &pid_val);
    assert(CPARSER_OK == rc);
    pid_ptr = &pid_val;
    rc = cparser_get_string(&parser->tokens[4], &filename_val);
    assert(CPARSER_OK == rc);
    filename_ptr = &filename_val;
    rc = cparser_get_int(&parser->tokens[6], &interval_val);
    if (CPARSER_OK == rc) {
        interval_ptr = &interval_val;
    } else {
        assert(7 > parser->token_tos);
    }
    cparser_cmd_add__p_pid__f_filename__i_interval(&parser->context,
        pid_ptr,
        filename_ptr,
        interval_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_add__e_executable (cparser_t *parser)
{
    char *executable_val;
    char **executable_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[2], &executable_val);
    assert(CPARSER_OK == rc);
    executable_ptr = &executable_val;
    cparser_cmd_add__e_executable(&parser->context,
        executable_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_add__e_executable__i_interval__f_filename (cparser_t *parser)
{
    char *executable_val;
    char **executable_ptr = NULL;
    int32_t interval_val;
    int32_t *interval_ptr = NULL;
    char *filename_val;
    char **filename_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[2], &executable_val);
    assert(CPARSER_OK == rc);
    executable_ptr = &executable_val;
    rc = cparser_get_int(&parser->tokens[4], &interval_val);
    assert(CPARSER_OK == rc);
    interval_ptr = &interval_val;
    rc = cparser_get_string(&parser->tokens[6], &filename_val);
    if (CPARSER_OK == rc) {
        filename_ptr = &filename_val;
    } else {
        assert(7 > parser->token_tos);
    }
    cparser_cmd_add__e_executable__i_interval__f_filename(&parser->context,
        executable_ptr,
        interval_ptr,
        filename_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_add__e_executable__f_filename__i_interval (cparser_t *parser)
{
    char *executable_val;
    char **executable_ptr = NULL;
    char *filename_val;
    char **filename_ptr = NULL;
    int32_t interval_val;
    int32_t *interval_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[2], &executable_val);
    assert(CPARSER_OK == rc);
    executable_ptr = &executable_val;
    rc = cparser_get_string(&parser->tokens[4], &filename_val);
    assert(CPARSER_OK == rc);
    filename_ptr = &filename_val;
    rc = cparser_get_int(&parser->tokens[6], &interval_val);
    if (CPARSER_OK == rc) {
        interval_ptr = &interval_val;
    } else {
        assert(7 > parser->token_tos);
    }
    cparser_cmd_add__e_executable__f_filename__i_interval(&parser->context,
        executable_ptr,
        filename_ptr,
        interval_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_set_interval_interval (cparser_t *parser)
{
    int32_t interval_val;
    int32_t *interval_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_int(&parser->tokens[2], &interval_val);
    assert(CPARSER_OK == rc);
    interval_ptr = &interval_val;
    cparser_cmd_set_interval_interval(&parser->context,
        interval_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_set_logfile_logFileName (cparser_t *parser)
{
    char *logFileName_val;
    char **logFileName_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[2], &logFileName_val);
    assert(CPARSER_OK == rc);
    logFileName_ptr = &logFileName_val;
    cparser_cmd_set_logfile_logFileName(&parser->context,
        logFileName_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_listactive (cparser_t *parser)
{
    cparser_cmd_listactive(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_listcompleted (cparser_t *parser)
{
    cparser_cmd_listcompleted(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_remove__s (cparser_t *parser)
{
    cparser_cmd_remove__s(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_remove__t_threadID (cparser_t *parser)
{
    int32_t threadID_val;
    int32_t *threadID_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_int(&parser->tokens[2], &threadID_val);
    assert(CPARSER_OK == rc);
    threadID_ptr = &threadID_val;
    cparser_cmd_remove__t_threadID(&parser->context,
        threadID_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_kill_processID (cparser_t *parser)
{
    int32_t processID_val;
    int32_t *processID_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_int(&parser->tokens[1], &processID_val);
    assert(CPARSER_OK == rc);
    processID_ptr = &processID_val;
    cparser_cmd_kill_processID(&parser->context,
        processID_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_help_filter (cparser_t *parser)
{
    char *filter_val;
    char **filter_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[1], &filter_val);
    if (CPARSER_OK == rc) {
        filter_ptr = &filter_val;
    } else {
        assert(2 > parser->token_tos);
    }
    cparser_cmd_help_filter(&parser->context,
        filter_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_exit (cparser_t *parser)
{
    cparser_cmd_exit(&parser->context);
    return CPARSER_OK;
}

cparser_node_t cparser_node_exit_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_exit,
    "Exit the application (display warning if active monitors exist)",
    NULL,
    NULL
};

cparser_node_t cparser_node_exit = {
    CPARSER_NODE_KEYWORD,
    0,
    "exit",
    NULL,
    NULL,
    &cparser_node_exit_eol
};

cparser_node_t cparser_node_help_filter_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_help_filter,
    "List all available commands with a substring 'filter' in it.",
    NULL,
    NULL
};

cparser_node_t cparser_node_help_filter = {
    CPARSER_NODE_STRING,
    CPARSER_NODE_FLAGS_OPT_START | CPARSER_NODE_FLAGS_OPT_END,
    "<STRING:filter>",
    NULL,
    NULL,
    &cparser_node_help_filter_eol
};

cparser_node_t cparser_node_help_eol = {
    CPARSER_NODE_END,
    CPARSER_NODE_FLAGS_OPT_PARTIAL,
    cparser_glue_help_filter,
    NULL,
    &cparser_node_help_filter,
    NULL
};

cparser_node_t cparser_node_help = {
    CPARSER_NODE_KEYWORD,
    0,
    "help",
    NULL,
    &cparser_node_exit,
    &cparser_node_help_eol
};

cparser_node_t cparser_node_kill_processID_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_kill_processID,
    "Terminate all threads associated with the process processID, then terminate the process",
    NULL,
    NULL
};

cparser_node_t cparser_node_kill_processID = {
    CPARSER_NODE_INT,
    0,
    "<INT:processID>",
    NULL,
    NULL,
    &cparser_node_kill_processID_eol
};

cparser_node_t cparser_node_kill = {
    CPARSER_NODE_KEYWORD,
    0,
    "kill",
    NULL,
    &cparser_node_help,
    &cparser_node_kill_processID
};

cparser_node_t cparser_node_remove__t_threadID_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_remove__t_threadID,
    "Remove a specific process monitor thread",
    NULL,
    NULL
};

cparser_node_t cparser_node_remove__t_threadID = {
    CPARSER_NODE_INT,
    0,
    "<INT:threadID>",
    NULL,
    NULL,
    &cparser_node_remove__t_threadID_eol
};

cparser_node_t cparser_node_remove__t = {
    CPARSER_NODE_KEYWORD,
    0,
    "-t",
    NULL,
    NULL,
    &cparser_node_remove__t_threadID
};

cparser_node_t cparser_node_remove__s_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_remove__s,
    "Remove the system monitor thread",
    NULL,
    NULL
};

cparser_node_t cparser_node_remove__s = {
    CPARSER_NODE_KEYWORD,
    0,
    "-s",
    NULL,
    &cparser_node_remove__t,
    &cparser_node_remove__s_eol
};

cparser_node_t cparser_node_remove = {
    CPARSER_NODE_KEYWORD,
    0,
    "remove",
    NULL,
    &cparser_node_kill,
    &cparser_node_remove__s
};

cparser_node_t cparser_node_listcompleted_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_listcompleted,
    "Show monitors which have been stopped (both manually or from exited process)",
    NULL,
    NULL
};

cparser_node_t cparser_node_listcompleted = {
    CPARSER_NODE_KEYWORD,
    0,
    "listcompleted",
    NULL,
    &cparser_node_remove,
    &cparser_node_listcompleted_eol
};

cparser_node_t cparser_node_listactive_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_listactive,
    "Show information about active monitors",
    NULL,
    NULL
};

cparser_node_t cparser_node_listactive = {
    CPARSER_NODE_KEYWORD,
    0,
    "listactive",
    NULL,
    &cparser_node_listcompleted,
    &cparser_node_listactive_eol
};

cparser_node_t cparser_node_set_logfile_logFileName_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_set_logfile_logFileName,
    "Set the default log file",
    NULL,
    NULL
};

cparser_node_t cparser_node_set_logfile_logFileName = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:logFileName>",
    NULL,
    NULL,
    &cparser_node_set_logfile_logFileName_eol
};

cparser_node_t cparser_node_set_logfile = {
    CPARSER_NODE_KEYWORD,
    0,
    "logfile",
    NULL,
    NULL,
    &cparser_node_set_logfile_logFileName
};

cparser_node_t cparser_node_set_interval_interval_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_set_interval_interval,
    "Set the default interval (in units of microseconds)",
    NULL,
    NULL
};

cparser_node_t cparser_node_set_interval_interval = {
    CPARSER_NODE_INT,
    0,
    "<INT:interval>",
    NULL,
    NULL,
    &cparser_node_set_interval_interval_eol
};

cparser_node_t cparser_node_set_interval = {
    CPARSER_NODE_KEYWORD,
    0,
    "interval",
    NULL,
    &cparser_node_set_logfile,
    &cparser_node_set_interval_interval
};

cparser_node_t cparser_node_set = {
    CPARSER_NODE_KEYWORD,
    0,
    "set",
    NULL,
    &cparser_node_listactive,
    &cparser_node_set_interval
};

cparser_node_t cparser_node_add__e_executable__f_filename__i_interval_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_add__e_executable__f_filename__i_interval,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_add__e_executable__f_filename__i_interval = {
    CPARSER_NODE_INT,
    CPARSER_NODE_FLAGS_OPT_END,
    "<INT:interval>",
    NULL,
    NULL,
    &cparser_node_add__e_executable__f_filename__i_interval_eol
};

cparser_node_t cparser_node_add__e_executable__f_filename__i = {
    CPARSER_NODE_KEYWORD,
    CPARSER_NODE_FLAGS_OPT_PARTIAL | CPARSER_NODE_FLAGS_OPT_START,
    "-i",
    NULL,
    NULL,
    &cparser_node_add__e_executable__f_filename__i_interval
};

cparser_node_t cparser_node_add__e_executable__f_filename_eol = {
    CPARSER_NODE_END,
    CPARSER_NODE_FLAGS_OPT_PARTIAL,
    cparser_glue_add__e_executable__f_filename__i_interval,
    NULL,
    &cparser_node_add__e_executable__f_filename__i,
    NULL
};

cparser_node_t cparser_node_add__e_executable__f_filename = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:filename>",
    NULL,
    NULL,
    &cparser_node_add__e_executable__f_filename_eol
};

cparser_node_t cparser_node_add__e_executable__f = {
    CPARSER_NODE_KEYWORD,
    0,
    "-f",
    NULL,
    NULL,
    &cparser_node_add__e_executable__f_filename
};

cparser_node_t cparser_node_add__e_executable__i_interval__f_filename_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_add__e_executable__i_interval__f_filename,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_add__e_executable__i_interval__f_filename = {
    CPARSER_NODE_STRING,
    CPARSER_NODE_FLAGS_OPT_END,
    "<STRING:filename>",
    NULL,
    NULL,
    &cparser_node_add__e_executable__i_interval__f_filename_eol
};

cparser_node_t cparser_node_add__e_executable__i_interval__f = {
    CPARSER_NODE_KEYWORD,
    CPARSER_NODE_FLAGS_OPT_PARTIAL | CPARSER_NODE_FLAGS_OPT_START,
    "-f",
    NULL,
    NULL,
    &cparser_node_add__e_executable__i_interval__f_filename
};

cparser_node_t cparser_node_add__e_executable__i_interval_eol = {
    CPARSER_NODE_END,
    CPARSER_NODE_FLAGS_OPT_PARTIAL,
    cparser_glue_add__e_executable__i_interval__f_filename,
    NULL,
    &cparser_node_add__e_executable__i_interval__f,
    NULL
};

cparser_node_t cparser_node_add__e_executable__i_interval = {
    CPARSER_NODE_INT,
    0,
    "<INT:interval>",
    NULL,
    NULL,
    &cparser_node_add__e_executable__i_interval_eol
};

cparser_node_t cparser_node_add__e_executable__i = {
    CPARSER_NODE_KEYWORD,
    0,
    "-i",
    NULL,
    &cparser_node_add__e_executable__f,
    &cparser_node_add__e_executable__i_interval
};

cparser_node_t cparser_node_add__e_executable_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_add__e_executable,
    "Exec executable and add a process monitor",
    &cparser_node_add__e_executable__i,
    NULL
};

cparser_node_t cparser_node_add__e_executable = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:executable>",
    NULL,
    NULL,
    &cparser_node_add__e_executable_eol
};

cparser_node_t cparser_node_add__e = {
    CPARSER_NODE_KEYWORD,
    0,
    "-e",
    NULL,
    NULL,
    &cparser_node_add__e_executable
};

cparser_node_t cparser_node_add__p_pid__f_filename__i_interval_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_add__p_pid__f_filename__i_interval,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_add__p_pid__f_filename__i_interval = {
    CPARSER_NODE_INT,
    CPARSER_NODE_FLAGS_OPT_END,
    "<INT:interval>",
    NULL,
    NULL,
    &cparser_node_add__p_pid__f_filename__i_interval_eol
};

cparser_node_t cparser_node_add__p_pid__f_filename__i = {
    CPARSER_NODE_KEYWORD,
    CPARSER_NODE_FLAGS_OPT_PARTIAL | CPARSER_NODE_FLAGS_OPT_START,
    "-i",
    NULL,
    NULL,
    &cparser_node_add__p_pid__f_filename__i_interval
};

cparser_node_t cparser_node_add__p_pid__f_filename_eol = {
    CPARSER_NODE_END,
    CPARSER_NODE_FLAGS_OPT_PARTIAL,
    cparser_glue_add__p_pid__f_filename__i_interval,
    NULL,
    &cparser_node_add__p_pid__f_filename__i,
    NULL
};

cparser_node_t cparser_node_add__p_pid__f_filename = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:filename>",
    NULL,
    NULL,
    &cparser_node_add__p_pid__f_filename_eol
};

cparser_node_t cparser_node_add__p_pid__f = {
    CPARSER_NODE_KEYWORD,
    0,
    "-f",
    NULL,
    NULL,
    &cparser_node_add__p_pid__f_filename
};

cparser_node_t cparser_node_add__p_pid__i_interval__f_filename_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_add__p_pid__i_interval__f_filename,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_add__p_pid__i_interval__f_filename = {
    CPARSER_NODE_STRING,
    CPARSER_NODE_FLAGS_OPT_END,
    "<STRING:filename>",
    NULL,
    NULL,
    &cparser_node_add__p_pid__i_interval__f_filename_eol
};

cparser_node_t cparser_node_add__p_pid__i_interval__f = {
    CPARSER_NODE_KEYWORD,
    CPARSER_NODE_FLAGS_OPT_PARTIAL | CPARSER_NODE_FLAGS_OPT_START,
    "-f",
    NULL,
    NULL,
    &cparser_node_add__p_pid__i_interval__f_filename
};

cparser_node_t cparser_node_add__p_pid__i_interval_eol = {
    CPARSER_NODE_END,
    CPARSER_NODE_FLAGS_OPT_PARTIAL,
    cparser_glue_add__p_pid__i_interval__f_filename,
    NULL,
    &cparser_node_add__p_pid__i_interval__f,
    NULL
};

cparser_node_t cparser_node_add__p_pid__i_interval = {
    CPARSER_NODE_INT,
    0,
    "<INT:interval>",
    NULL,
    NULL,
    &cparser_node_add__p_pid__i_interval_eol
};

cparser_node_t cparser_node_add__p_pid__i = {
    CPARSER_NODE_KEYWORD,
    0,
    "-i",
    NULL,
    &cparser_node_add__p_pid__f,
    &cparser_node_add__p_pid__i_interval
};

cparser_node_t cparser_node_add__p_pid_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_add__p_pid,
    "Add process monitor to the active process with pid",
    &cparser_node_add__p_pid__i,
    NULL
};

cparser_node_t cparser_node_add__p_pid = {
    CPARSER_NODE_INT,
    0,
    "<INT:pid>",
    NULL,
    NULL,
    &cparser_node_add__p_pid_eol
};

cparser_node_t cparser_node_add__p = {
    CPARSER_NODE_KEYWORD,
    0,
    "-p",
    NULL,
    &cparser_node_add__e,
    &cparser_node_add__p_pid
};

cparser_node_t cparser_node_add__s__f_filename__i_interval_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_add__s__f_filename__i_interval,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_add__s__f_filename__i_interval = {
    CPARSER_NODE_INT,
    CPARSER_NODE_FLAGS_OPT_END,
    "<INT:interval>",
    NULL,
    NULL,
    &cparser_node_add__s__f_filename__i_interval_eol
};

cparser_node_t cparser_node_add__s__f_filename__i = {
    CPARSER_NODE_KEYWORD,
    CPARSER_NODE_FLAGS_OPT_PARTIAL | CPARSER_NODE_FLAGS_OPT_START,
    "-i",
    NULL,
    NULL,
    &cparser_node_add__s__f_filename__i_interval
};

cparser_node_t cparser_node_add__s__f_filename_eol = {
    CPARSER_NODE_END,
    CPARSER_NODE_FLAGS_OPT_PARTIAL,
    cparser_glue_add__s__f_filename__i_interval,
    NULL,
    &cparser_node_add__s__f_filename__i,
    NULL
};

cparser_node_t cparser_node_add__s__f_filename = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:filename>",
    NULL,
    NULL,
    &cparser_node_add__s__f_filename_eol
};

cparser_node_t cparser_node_add__s__f = {
    CPARSER_NODE_KEYWORD,
    0,
    "-f",
    NULL,
    NULL,
    &cparser_node_add__s__f_filename
};

cparser_node_t cparser_node_add__s__i_interval__f_filename_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_add__s__i_interval__f_filename,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_add__s__i_interval__f_filename = {
    CPARSER_NODE_STRING,
    CPARSER_NODE_FLAGS_OPT_END,
    "<STRING:filename>",
    NULL,
    NULL,
    &cparser_node_add__s__i_interval__f_filename_eol
};

cparser_node_t cparser_node_add__s__i_interval__f = {
    CPARSER_NODE_KEYWORD,
    CPARSER_NODE_FLAGS_OPT_PARTIAL | CPARSER_NODE_FLAGS_OPT_START,
    "-f",
    NULL,
    NULL,
    &cparser_node_add__s__i_interval__f_filename
};

cparser_node_t cparser_node_add__s__i_interval_eol = {
    CPARSER_NODE_END,
    CPARSER_NODE_FLAGS_OPT_PARTIAL,
    cparser_glue_add__s__i_interval__f_filename,
    NULL,
    &cparser_node_add__s__i_interval__f,
    NULL
};

cparser_node_t cparser_node_add__s__i_interval = {
    CPARSER_NODE_INT,
    0,
    "<INT:interval>",
    NULL,
    NULL,
    &cparser_node_add__s__i_interval_eol
};

cparser_node_t cparser_node_add__s__i = {
    CPARSER_NODE_KEYWORD,
    0,
    "-i",
    NULL,
    &cparser_node_add__s__f,
    &cparser_node_add__s__i_interval
};

cparser_node_t cparser_node_add__s_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_add__s,
    "Add system monitor",
    &cparser_node_add__s__i,
    NULL
};

cparser_node_t cparser_node_add__s = {
    CPARSER_NODE_KEYWORD,
    0,
    "-s",
    NULL,
    &cparser_node_add__p,
    &cparser_node_add__s_eol
};

cparser_node_t cparser_node_add = {
    CPARSER_NODE_KEYWORD,
    0,
    "add",
    NULL,
    &cparser_node_set,
    &cparser_node_add__s
};

cparser_node_t cparser_root = {
    CPARSER_NODE_ROOT,
    0,
    NULL,
    "Root node of the parser tree",
    NULL,
    &cparser_node_add
};

